import random
digit1 = random.randint(0, 9)
digit2 = random.randint(0, 9)
digit3 = random.randint(0, 9)
print(f"The 3-digit code is: {digit1}{digit2}{digit3}")
num1 = random.randint(1, 6)
num2 = random.randint(1, 6)
num3 = random.randint(1, 6)
num4 = random.randint(1, 6)
print(f"The 4-digit code is: {num1}{num2}{num3}{num4}")